import {
  DEPARTURE_WATCHDOG_MIN_MS,
  DEPARTURE_WATCHDOG_MIN_MS_MAX_RELIABILITY,
  DRIVE_GPS_WAKE_SPEED_MS,
  HEARTBEAT_CHECK_INTERVAL_SEC,
  HEARTBEAT_CHECK_INTERVAL_SEC_MAX_RELIABILITY,
  HEARTBEAT_DEPARTURE_DISTANCE_METERS,
  HEARTBEAT_DESIRED_ACCURACY_METERS,
  MAX_DEPARTURE_ACCURACY_METERS,
  MAX_PLAUSIBLE_SPEED_MS,
  MIN_DEPARTURE_SPEED_MS,
  SAME_PLACE_LINE_BREAK_MS,
  STATIONARY_PING_MIN_MS,
  STATIONARY_PING_MIN_MS_MAX_RELIABILITY,
} from '@/lib/app-constants';

export {
  DEPARTURE_WATCHDOG_MIN_MS,
  DEPARTURE_WATCHDOG_MIN_MS_MAX_RELIABILITY,
  DRIVE_GPS_WAKE_SPEED_MS,
  HEARTBEAT_CHECK_INTERVAL_SEC,
  HEARTBEAT_CHECK_INTERVAL_SEC_MAX_RELIABILITY,
  HEARTBEAT_DEPARTURE_DISTANCE_METERS,
  HEARTBEAT_DESIRED_ACCURACY_METERS,
  MAX_DEPARTURE_ACCURACY_METERS,
  MAX_PLAUSIBLE_SPEED_MS,
  MIN_DEPARTURE_SPEED_MS,
  SAME_PLACE_LINE_BREAK_MS,
  STATIONARY_PING_MIN_MS,
  STATIONARY_PING_MIN_MS_MAX_RELIABILITY,
};

/** Stopping threshold for heartbeat getCurrentPosition — see CurrentPositionRequest. */
export const HEARTBEAT_CURRENT_POSITION_REQUEST = {
  desiredAccuracy: HEARTBEAT_DESIRED_ACCURACY_METERS,
  timeout: 30,
  maximumAge: 0,
  samples: 1,
  persist: false,
} as const;
