import type { ImageSourcePropType } from 'react-native';
import type { EmotionTokenId } from '@/lib/moments/emotion-tokens';
import type { MoodArtVariant } from '@/lib/moments/mood-art';

export const MOOD_ART_ASSETS: Record<
  EmotionTokenId,
  Record<MoodArtVariant, ImageSourcePropType>
> = {
  achy: {
    male: require('../../../assets/moods/achy/male.png'),
    female: require('../../../assets/moods/achy/female.png'),
    cat: require('../../../assets/moods/achy/cat.png'),
    dog: require('../../../assets/moods/achy/dog.png'),
  },
  affectionate: {
    male: require('../../../assets/moods/affectionate/male.png'),
    female: require('../../../assets/moods/affectionate/female.png'),
    cat: require('../../../assets/moods/affectionate/cat.png'),
    dog: require('../../../assets/moods/affectionate/dog.png'),
  },
  amazed: {
    male: require('../../../assets/moods/amazed/male.png'),
    female: require('../../../assets/moods/amazed/female.png'),
    cat: require('../../../assets/moods/amazed/cat.png'),
    dog: require('../../../assets/moods/amazed/dog.png'),
  },
  amused: {
    male: require('../../../assets/moods/amused/male.png'),
    female: require('../../../assets/moods/amused/female.png'),
    cat: require('../../../assets/moods/amused/cat.png'),
    dog: require('../../../assets/moods/amused/dog.png'),
  },
  angry: {
    male: require('../../../assets/moods/angry/male.png'),
    female: require('../../../assets/moods/angry/female.png'),
    cat: require('../../../assets/moods/angry/cat.png'),
    dog: require('../../../assets/moods/angry/dog.png'),
  },
  annoyed: {
    male: require('../../../assets/moods/annoyed/male.png'),
    female: require('../../../assets/moods/annoyed/female.png'),
    cat: require('../../../assets/moods/annoyed/cat.png'),
    dog: require('../../../assets/moods/annoyed/dog.png'),
  },
  anxious: {
    male: require('../../../assets/moods/anxious/male.png'),
    female: require('../../../assets/moods/anxious/female.png'),
    cat: require('../../../assets/moods/anxious/cat.png'),
    dog: require('../../../assets/moods/anxious/dog.png'),
  },
  ashamed: {
    male: require('../../../assets/moods/ashamed/male.png'),
    female: require('../../../assets/moods/ashamed/female.png'),
    cat: require('../../../assets/moods/ashamed/cat.png'),
    dog: require('../../../assets/moods/ashamed/dog.png'),
  },
  bitter: {
    male: require('../../../assets/moods/bitter/male.png'),
    female: require('../../../assets/moods/bitter/female.png'),
    cat: require('../../../assets/moods/bitter/cat.png'),
    dog: require('../../../assets/moods/bitter/dog.png'),
  },
  bored: {
    male: require('../../../assets/moods/bored/male.png'),
    female: require('../../../assets/moods/bored/female.png'),
    cat: require('../../../assets/moods/bored/cat.png'),
    dog: require('../../../assets/moods/bored/dog.png'),
  },
  brave: {
    male: require('../../../assets/moods/brave/male.png'),
    female: require('../../../assets/moods/brave/female.png'),
    cat: require('../../../assets/moods/brave/cat.png'),
    dog: require('../../../assets/moods/brave/dog.png'),
  },
  breathless: {
    male: require('../../../assets/moods/breathless/male.png'),
    female: require('../../../assets/moods/breathless/female.png'),
    cat: require('../../../assets/moods/breathless/cat.png'),
    dog: require('../../../assets/moods/breathless/dog.png'),
  },
  burnedout: {
    male: require('../../../assets/moods/burnedout/male.png'),
    female: require('../../../assets/moods/burnedout/female.png'),
    cat: require('../../../assets/moods/burnedout/cat.png'),
    dog: require('../../../assets/moods/burnedout/dog.png'),
  },
  calm: {
    male: require('../../../assets/moods/calm/male.png'),
    female: require('../../../assets/moods/calm/female.png'),
    cat: require('../../../assets/moods/calm/cat.png'),
    dog: require('../../../assets/moods/calm/dog.png'),
  },
  caring: {
    male: require('../../../assets/moods/caring/male.png'),
    female: require('../../../assets/moods/caring/female.png'),
    cat: require('../../../assets/moods/caring/cat.png'),
    dog: require('../../../assets/moods/caring/dog.png'),
  },
  clenched: {
    male: require('../../../assets/moods/clenched/male.png'),
    female: require('../../../assets/moods/clenched/female.png'),
    cat: require('../../../assets/moods/clenched/cat.png'),
    dog: require('../../../assets/moods/clenched/dog.png'),
  },
  cold: {
    male: require('../../../assets/moods/cold/male.png'),
    female: require('../../../assets/moods/cold/female.png'),
    cat: require('../../../assets/moods/cold/cat.png'),
    dog: require('../../../assets/moods/cold/dog.png'),
  },
  confident: {
    male: require('../../../assets/moods/confident/male.png'),
    female: require('../../../assets/moods/confident/female.png'),
    cat: require('../../../assets/moods/confident/cat.png'),
    dog: require('../../../assets/moods/confident/dog.png'),
  },
  confused: {
    male: require('../../../assets/moods/confused/male.png'),
    female: require('../../../assets/moods/confused/female.png'),
    cat: require('../../../assets/moods/confused/cat.png'),
    dog: require('../../../assets/moods/confused/dog.png'),
  },
  content: {
    male: require('../../../assets/moods/content/male.png'),
    female: require('../../../assets/moods/content/female.png'),
    cat: require('../../../assets/moods/content/cat.png'),
    dog: require('../../../assets/moods/content/dog.png'),
  },
  curious: {
    male: require('../../../assets/moods/curious/male.png'),
    female: require('../../../assets/moods/curious/female.png'),
    cat: require('../../../assets/moods/curious/cat.png'),
    dog: require('../../../assets/moods/curious/dog.png'),
  },
  daring: {
    male: require('../../../assets/moods/daring/male.png'),
    female: require('../../../assets/moods/daring/female.png'),
    cat: require('../../../assets/moods/daring/cat.png'),
    dog: require('../../../assets/moods/daring/dog.png'),
  },
  depressed: {
    male: require('../../../assets/moods/depressed/male.png'),
    female: require('../../../assets/moods/depressed/female.png'),
    cat: require('../../../assets/moods/depressed/cat.png'),
    dog: require('../../../assets/moods/depressed/dog.png'),
  },
  determined: {
    male: require('../../../assets/moods/determined/male.png'),
    female: require('../../../assets/moods/determined/female.png'),
    cat: require('../../../assets/moods/determined/cat.png'),
    dog: require('../../../assets/moods/determined/dog.png'),
  },
  disappointed: {
    male: require('../../../assets/moods/disappointed/male.png'),
    female: require('../../../assets/moods/disappointed/female.png'),
    cat: require('../../../assets/moods/disappointed/cat.png'),
    dog: require('../../../assets/moods/disappointed/dog.png'),
  },
  discouraged: {
    male: require('../../../assets/moods/discouraged/male.png'),
    female: require('../../../assets/moods/discouraged/female.png'),
    cat: require('../../../assets/moods/discouraged/cat.png'),
    dog: require('../../../assets/moods/discouraged/dog.png'),
  },
  disgusted: {
    male: require('../../../assets/moods/disgusted/male.png'),
    female: require('../../../assets/moods/disgusted/female.png'),
    cat: require('../../../assets/moods/disgusted/cat.png'),
    dog: require('../../../assets/moods/disgusted/dog.png'),
  },
  dizzy: {
    male: require('../../../assets/moods/dizzy/male.png'),
    female: require('../../../assets/moods/dizzy/female.png'),
    cat: require('../../../assets/moods/dizzy/cat.png'),
    dog: require('../../../assets/moods/dizzy/dog.png'),
  },
  drained: {
    male: require('../../../assets/moods/drained/male.png'),
    female: require('../../../assets/moods/drained/female.png'),
    cat: require('../../../assets/moods/drained/cat.png'),
    dog: require('../../../assets/moods/drained/dog.png'),
  },
  embarrassed: {
    male: require('../../../assets/moods/embarrassed/male.png'),
    female: require('../../../assets/moods/embarrassed/female.png'),
    cat: require('../../../assets/moods/embarrassed/cat.png'),
    dog: require('../../../assets/moods/embarrassed/dog.png'),
  },
  empty: {
    male: require('../../../assets/moods/empty/male.png'),
    female: require('../../../assets/moods/empty/female.png'),
    cat: require('../../../assets/moods/empty/cat.png'),
    dog: require('../../../assets/moods/empty/dog.png'),
  },
  empathy: {
    male: require('../../../assets/moods/empathy/male.png'),
    female: require('../../../assets/moods/empathy/female.png'),
    cat: require('../../../assets/moods/empathy/cat.png'),
    dog: require('../../../assets/moods/empathy/dog.png'),
  },
  energized: {
    male: require('../../../assets/moods/energized/male.png'),
    female: require('../../../assets/moods/energized/female.png'),
    cat: require('../../../assets/moods/energized/cat.png'),
    dog: require('../../../assets/moods/energized/dog.png'),
  },
  excited: {
    male: require('../../../assets/moods/excited/male.png'),
    female: require('../../../assets/moods/excited/female.png'),
    cat: require('../../../assets/moods/excited/cat.png'),
    dog: require('../../../assets/moods/excited/dog.png'),
  },
  frozen: {
    male: require('../../../assets/moods/frozen/male.png'),
    female: require('../../../assets/moods/frozen/female.png'),
    cat: require('../../../assets/moods/frozen/cat.png'),
    dog: require('../../../assets/moods/frozen/dog.png'),
  },
  frustrated: {
    male: require('../../../assets/moods/frustrated/male.png'),
    female: require('../../../assets/moods/frustrated/female.png'),
    cat: require('../../../assets/moods/frustrated/cat.png'),
    dog: require('../../../assets/moods/frustrated/dog.png'),
  },
  furious: {
    male: require('../../../assets/moods/furious/male.png'),
    female: require('../../../assets/moods/furious/female.png'),
    cat: require('../../../assets/moods/furious/cat.png'),
    dog: require('../../../assets/moods/furious/dog.png'),
  },
  grateful: {
    male: require('../../../assets/moods/grateful/male.png'),
    female: require('../../../assets/moods/grateful/female.png'),
    cat: require('../../../assets/moods/grateful/cat.png'),
    dog: require('../../../assets/moods/grateful/dog.png'),
  },
  grief: {
    male: require('../../../assets/moods/grief/male.png'),
    female: require('../../../assets/moods/grief/female.png'),
    cat: require('../../../assets/moods/grief/cat.png'),
    dog: require('../../../assets/moods/grief/dog.png'),
  },
  grounded: {
    male: require('../../../assets/moods/grounded/male.png'),
    female: require('../../../assets/moods/grounded/female.png'),
    cat: require('../../../assets/moods/grounded/cat.png'),
    dog: require('../../../assets/moods/grounded/dog.png'),
  },
  guilty: {
    male: require('../../../assets/moods/guilty/male.png'),
    female: require('../../../assets/moods/guilty/female.png'),
    cat: require('../../../assets/moods/guilty/cat.png'),
    dog: require('../../../assets/moods/guilty/dog.png'),
  },
  happy: {
    male: require('../../../assets/moods/happy/male.png'),
    female: require('../../../assets/moods/happy/female.png'),
    cat: require('../../../assets/moods/happy/cat.png'),
    dog: require('../../../assets/moods/happy/dog.png'),
  },
  heartbroken: {
    male: require('../../../assets/moods/heartbroken/male.png'),
    female: require('../../../assets/moods/heartbroken/female.png'),
    cat: require('../../../assets/moods/heartbroken/cat.png'),
    dog: require('../../../assets/moods/heartbroken/dog.png'),
  },
  heavy: {
    male: require('../../../assets/moods/heavy/male.png'),
    female: require('../../../assets/moods/heavy/female.png'),
    cat: require('../../../assets/moods/heavy/cat.png'),
    dog: require('../../../assets/moods/heavy/dog.png'),
  },
  helpless: {
    male: require('../../../assets/moods/helpless/male.png'),
    female: require('../../../assets/moods/helpless/female.png'),
    cat: require('../../../assets/moods/helpless/cat.png'),
    dog: require('../../../assets/moods/helpless/dog.png'),
  },
  hollow: {
    male: require('../../../assets/moods/hollow/male.png'),
    female: require('../../../assets/moods/hollow/female.png'),
    cat: require('../../../assets/moods/hollow/cat.png'),
    dog: require('../../../assets/moods/hollow/dog.png'),
  },
  hopeful: {
    male: require('../../../assets/moods/hopeful/male.png'),
    female: require('../../../assets/moods/hopeful/female.png'),
    cat: require('../../../assets/moods/hopeful/cat.png'),
    dog: require('../../../assets/moods/hopeful/dog.png'),
  },
  hot: {
    male: require('../../../assets/moods/hot/male.png'),
    female: require('../../../assets/moods/hot/female.png'),
    cat: require('../../../assets/moods/hot/cat.png'),
    dog: require('../../../assets/moods/hot/dog.png'),
  },
  impatient: {
    male: require('../../../assets/moods/impatient/male.png'),
    female: require('../../../assets/moods/impatient/female.png'),
    cat: require('../../../assets/moods/impatient/cat.png'),
    dog: require('../../../assets/moods/impatient/dog.png'),
  },
  indifferent: {
    male: require('../../../assets/moods/indifferent/male.png'),
    female: require('../../../assets/moods/indifferent/female.png'),
    cat: require('../../../assets/moods/indifferent/cat.png'),
    dog: require('../../../assets/moods/indifferent/dog.png'),
  },
  insecure: {
    male: require('../../../assets/moods/insecure/male.png'),
    female: require('../../../assets/moods/insecure/female.png'),
    cat: require('../../../assets/moods/insecure/cat.png'),
    dog: require('../../../assets/moods/insecure/dog.png'),
  },
  inspired: {
    male: require('../../../assets/moods/inspired/male.png'),
    female: require('../../../assets/moods/inspired/female.png'),
    cat: require('../../../assets/moods/inspired/cat.png'),
    dog: require('../../../assets/moods/inspired/dog.png'),
  },
  irritated: {
    male: require('../../../assets/moods/irritated/male.png'),
    female: require('../../../assets/moods/irritated/female.png'),
    cat: require('../../../assets/moods/irritated/cat.png'),
    dog: require('../../../assets/moods/irritated/dog.png'),
  },
  isolated: {
    male: require('../../../assets/moods/isolated/male.png'),
    female: require('../../../assets/moods/isolated/female.png'),
    cat: require('../../../assets/moods/isolated/cat.png'),
    dog: require('../../../assets/moods/isolated/dog.png'),
  },
  jealous: {
    male: require('../../../assets/moods/jealous/male.png'),
    female: require('../../../assets/moods/jealous/female.png'),
    cat: require('../../../assets/moods/jealous/cat.png'),
    dog: require('../../../assets/moods/jealous/dog.png'),
  },
  joyful: {
    male: require('../../../assets/moods/joyful/male.png'),
    female: require('../../../assets/moods/joyful/female.png'),
    cat: require('../../../assets/moods/joyful/cat.png'),
    dog: require('../../../assets/moods/joyful/dog.png'),
  },
  knotted: {
    male: require('../../../assets/moods/knotted/male.png'),
    female: require('../../../assets/moods/knotted/female.png'),
    cat: require('../../../assets/moods/knotted/cat.png'),
    dog: require('../../../assets/moods/knotted/dog.png'),
  },
  light: {
    male: require('../../../assets/moods/light/male.png'),
    female: require('../../../assets/moods/light/female.png'),
    cat: require('../../../assets/moods/light/cat.png'),
    dog: require('../../../assets/moods/light/dog.png'),
  },
  lonely: {
    male: require('../../../assets/moods/lonely/male.png'),
    female: require('../../../assets/moods/lonely/female.png'),
    cat: require('../../../assets/moods/lonely/cat.png'),
    dog: require('../../../assets/moods/lonely/dog.png'),
  },
  longing: {
    male: require('../../../assets/moods/longing/male.png'),
    female: require('../../../assets/moods/longing/female.png'),
    cat: require('../../../assets/moods/longing/cat.png'),
    dog: require('../../../assets/moods/longing/dog.png'),
  },
  loved: {
    male: require('../../../assets/moods/loved/male.png'),
    female: require('../../../assets/moods/loved/female.png'),
    cat: require('../../../assets/moods/loved/cat.png'),
    dog: require('../../../assets/moods/loved/dog.png'),
  },
  lucky: {
    male: require('../../../assets/moods/lucky/male.png'),
    female: require('../../../assets/moods/lucky/female.png'),
    cat: require('../../../assets/moods/lucky/cat.png'),
    dog: require('../../../assets/moods/lucky/dog.png'),
  },
  melancholy: {
    male: require('../../../assets/moods/melancholy/male.png'),
    female: require('../../../assets/moods/melancholy/female.png'),
    cat: require('../../../assets/moods/melancholy/cat.png'),
    dog: require('../../../assets/moods/melancholy/dog.png'),
  },
  moody: {
    male: require('../../../assets/moods/moody/male.png'),
    female: require('../../../assets/moods/moody/female.png'),
    cat: require('../../../assets/moods/moody/cat.png'),
    dog: require('../../../assets/moods/moody/dog.png'),
  },
  motivated: {
    male: require('../../../assets/moods/motivated/male.png'),
    female: require('../../../assets/moods/motivated/female.png'),
    cat: require('../../../assets/moods/motivated/cat.png'),
    dog: require('../../../assets/moods/motivated/dog.png'),
  },
  nauseous: {
    male: require('../../../assets/moods/nauseous/male.png'),
    female: require('../../../assets/moods/nauseous/female.png'),
    cat: require('../../../assets/moods/nauseous/cat.png'),
    dog: require('../../../assets/moods/nauseous/dog.png'),
  },
  nervous: {
    male: require('../../../assets/moods/nervous/male.png'),
    female: require('../../../assets/moods/nervous/female.png'),
    cat: require('../../../assets/moods/nervous/cat.png'),
    dog: require('../../../assets/moods/nervous/dog.png'),
  },
  nostalgic: {
    male: require('../../../assets/moods/nostalgic/male.png'),
    female: require('../../../assets/moods/nostalgic/female.png'),
    cat: require('../../../assets/moods/nostalgic/cat.png'),
    dog: require('../../../assets/moods/nostalgic/dog.png'),
  },
  numb: {
    male: require('../../../assets/moods/numb/male.png'),
    female: require('../../../assets/moods/numb/female.png'),
    cat: require('../../../assets/moods/numb/cat.png'),
    dog: require('../../../assets/moods/numb/dog.png'),
  },
  optimistic: {
    male: require('../../../assets/moods/optimistic/male.png'),
    female: require('../../../assets/moods/optimistic/female.png'),
    cat: require('../../../assets/moods/optimistic/cat.png'),
    dog: require('../../../assets/moods/optimistic/dog.png'),
  },
  overwhelmed: {
    male: require('../../../assets/moods/overwhelmed/male.png'),
    female: require('../../../assets/moods/overwhelmed/female.png'),
    cat: require('../../../assets/moods/overwhelmed/cat.png'),
    dog: require('../../../assets/moods/overwhelmed/dog.png'),
  },
  panic: {
    male: require('../../../assets/moods/panic/male.png'),
    female: require('../../../assets/moods/panic/female.png'),
    cat: require('../../../assets/moods/panic/cat.png'),
    dog: require('../../../assets/moods/panic/dog.png'),
  },
  passionate: {
    male: require('../../../assets/moods/passionate/male.png'),
    female: require('../../../assets/moods/passionate/female.png'),
    cat: require('../../../assets/moods/passionate/cat.png'),
    dog: require('../../../assets/moods/passionate/dog.png'),
  },
  peaceful: {
    male: require('../../../assets/moods/peaceful/male.png'),
    female: require('../../../assets/moods/peaceful/female.png'),
    cat: require('../../../assets/moods/peaceful/cat.png'),
    dog: require('../../../assets/moods/peaceful/dog.png'),
  },
  pissed: {
    male: require('../../../assets/moods/pissed/male.png'),
    female: require('../../../assets/moods/pissed/female.png'),
    cat: require('../../../assets/moods/pissed/cat.png'),
    dog: require('../../../assets/moods/pissed/dog.png'),
  },
  playful: {
    male: require('../../../assets/moods/playful/male.png'),
    female: require('../../../assets/moods/playful/female.png'),
    cat: require('../../../assets/moods/playful/cat.png'),
    dog: require('../../../assets/moods/playful/dog.png'),
  },
  present: {
    male: require('../../../assets/moods/present/male.png'),
    female: require('../../../assets/moods/present/female.png'),
    cat: require('../../../assets/moods/present/cat.png'),
    dog: require('../../../assets/moods/present/dog.png'),
  },
  proud: {
    male: require('../../../assets/moods/proud/male.png'),
    female: require('../../../assets/moods/proud/female.png'),
    cat: require('../../../assets/moods/proud/cat.png'),
    dog: require('../../../assets/moods/proud/dog.png'),
  },
  regret: {
    male: require('../../../assets/moods/regret/male.png'),
    female: require('../../../assets/moods/regret/female.png'),
    cat: require('../../../assets/moods/regret/cat.png'),
    dog: require('../../../assets/moods/regret/dog.png'),
  },
  relaxed: {
    male: require('../../../assets/moods/relaxed/male.png'),
    female: require('../../../assets/moods/relaxed/female.png'),
    cat: require('../../../assets/moods/relaxed/cat.png'),
    dog: require('../../../assets/moods/relaxed/dog.png'),
  },
  relieved: {
    male: require('../../../assets/moods/relieved/male.png'),
    female: require('../../../assets/moods/relieved/female.png'),
    cat: require('../../../assets/moods/relieved/cat.png'),
    dog: require('../../../assets/moods/relieved/dog.png'),
  },
  resentful: {
    male: require('../../../assets/moods/resentful/male.png'),
    female: require('../../../assets/moods/resentful/female.png'),
    cat: require('../../../assets/moods/resentful/cat.png'),
    dog: require('../../../assets/moods/resentful/dog.png'),
  },
  restless: {
    male: require('../../../assets/moods/restless/male.png'),
    female: require('../../../assets/moods/restless/female.png'),
    cat: require('../../../assets/moods/restless/cat.png'),
    dog: require('../../../assets/moods/restless/dog.png'),
  },
  sad: {
    male: require('../../../assets/moods/sad/male.png'),
    female: require('../../../assets/moods/sad/female.png'),
    cat: require('../../../assets/moods/sad/cat.png'),
    dog: require('../../../assets/moods/sad/dog.png'),
  },
  safe: {
    male: require('../../../assets/moods/safe/male.png'),
    female: require('../../../assets/moods/safe/female.png'),
    cat: require('../../../assets/moods/safe/cat.png'),
    dog: require('../../../assets/moods/safe/dog.png'),
  },
  satisfied: {
    male: require('../../../assets/moods/satisfied/male.png'),
    female: require('../../../assets/moods/satisfied/female.png'),
    cat: require('../../../assets/moods/satisfied/cat.png'),
    dog: require('../../../assets/moods/satisfied/dog.png'),
  },
  scared: {
    male: require('../../../assets/moods/scared/male.png'),
    female: require('../../../assets/moods/scared/female.png'),
    cat: require('../../../assets/moods/scared/cat.png'),
    dog: require('../../../assets/moods/scared/dog.png'),
  },
  settled: {
    male: require('../../../assets/moods/settled/male.png'),
    female: require('../../../assets/moods/settled/female.png'),
    cat: require('../../../assets/moods/settled/cat.png'),
    dog: require('../../../assets/moods/settled/dog.png'),
  },
  shaky: {
    male: require('../../../assets/moods/shaky/male.png'),
    female: require('../../../assets/moods/shaky/female.png'),
    cat: require('../../../assets/moods/shaky/cat.png'),
    dog: require('../../../assets/moods/shaky/dog.png'),
  },
  shocked: {
    male: require('../../../assets/moods/shocked/male.png'),
    female: require('../../../assets/moods/shocked/female.png'),
    cat: require('../../../assets/moods/shocked/cat.png'),
    dog: require('../../../assets/moods/shocked/dog.png'),
  },
  sorry: {
    male: require('../../../assets/moods/sorry/male.png'),
    female: require('../../../assets/moods/sorry/female.png'),
    cat: require('../../../assets/moods/sorry/cat.png'),
    dog: require('../../../assets/moods/sorry/dog.png'),
  },
  stressed: {
    male: require('../../../assets/moods/stressed/male.png'),
    female: require('../../../assets/moods/stressed/female.png'),
    cat: require('../../../assets/moods/stressed/cat.png'),
    dog: require('../../../assets/moods/stressed/dog.png'),
  },
  strong: {
    male: require('../../../assets/moods/strong/male.png'),
    female: require('../../../assets/moods/strong/female.png'),
    cat: require('../../../assets/moods/strong/cat.png'),
    dog: require('../../../assets/moods/strong/dog.png'),
  },
  suffocated: {
    male: require('../../../assets/moods/suffocated/male.png'),
    female: require('../../../assets/moods/suffocated/female.png'),
    cat: require('../../../assets/moods/suffocated/cat.png'),
    dog: require('../../../assets/moods/suffocated/dog.png'),
  },
  surprised: {
    male: require('../../../assets/moods/surprised/male.png'),
    female: require('../../../assets/moods/surprised/female.png'),
    cat: require('../../../assets/moods/surprised/cat.png'),
    dog: require('../../../assets/moods/surprised/dog.png'),
  },
  tense: {
    male: require('../../../assets/moods/tense/male.png'),
    female: require('../../../assets/moods/tense/female.png'),
    cat: require('../../../assets/moods/tense/cat.png'),
    dog: require('../../../assets/moods/tense/dog.png'),
  },
  terrified: {
    male: require('../../../assets/moods/terrified/male.png'),
    female: require('../../../assets/moods/terrified/female.png'),
    cat: require('../../../assets/moods/terrified/cat.png'),
    dog: require('../../../assets/moods/terrified/dog.png'),
  },
  thankful: {
    male: require('../../../assets/moods/thankful/male.png'),
    female: require('../../../assets/moods/thankful/female.png'),
    cat: require('../../../assets/moods/thankful/cat.png'),
    dog: require('../../../assets/moods/thankful/dog.png'),
  },
  thrilled: {
    male: require('../../../assets/moods/thrilled/male.png'),
    female: require('../../../assets/moods/thrilled/female.png'),
    cat: require('../../../assets/moods/thrilled/cat.png'),
    dog: require('../../../assets/moods/thrilled/dog.png'),
  },
  tingling: {
    male: require('../../../assets/moods/tingling/male.png'),
    female: require('../../../assets/moods/tingling/female.png'),
    cat: require('../../../assets/moods/tingling/cat.png'),
    dog: require('../../../assets/moods/tingling/dog.png'),
  },
  tired: {
    male: require('../../../assets/moods/tired/male.png'),
    female: require('../../../assets/moods/tired/female.png'),
    cat: require('../../../assets/moods/tired/cat.png'),
    dog: require('../../../assets/moods/tired/dog.png'),
  },
  trusting: {
    male: require('../../../assets/moods/trusting/male.png'),
    female: require('../../../assets/moods/trusting/female.png'),
    cat: require('../../../assets/moods/trusting/cat.png'),
    dog: require('../../../assets/moods/trusting/dog.png'),
  },
  unhappy: {
    male: require('../../../assets/moods/unhappy/male.png'),
    female: require('../../../assets/moods/unhappy/female.png'),
    cat: require('../../../assets/moods/unhappy/cat.png'),
    dog: require('../../../assets/moods/unhappy/dog.png'),
  },
  upset: {
    male: require('../../../assets/moods/upset/male.png'),
    female: require('../../../assets/moods/upset/female.png'),
    cat: require('../../../assets/moods/upset/cat.png'),
    dog: require('../../../assets/moods/upset/dog.png'),
  },
  vulnerable: {
    male: require('../../../assets/moods/vulnerable/male.png'),
    female: require('../../../assets/moods/vulnerable/female.png'),
    cat: require('../../../assets/moods/vulnerable/cat.png'),
    dog: require('../../../assets/moods/vulnerable/dog.png'),
  },
  worried: {
    male: require('../../../assets/moods/worried/male.png'),
    female: require('../../../assets/moods/worried/female.png'),
    cat: require('../../../assets/moods/worried/cat.png'),
    dog: require('../../../assets/moods/worried/dog.png'),
  },
  worthy: {
    male: require('../../../assets/moods/worthy/male.png'),
    female: require('../../../assets/moods/worthy/female.png'),
    cat: require('../../../assets/moods/worthy/cat.png'),
    dog: require('../../../assets/moods/worthy/dog.png'),
  },
};
