import type { AchievementBadgeDefinition } from './types';

export const ACHIEVEMENT_BADGES: readonly AchievementBadgeDefinition[] = [
  // Traveler
  {
    id: 'travel_10',
    pillar: 'traveler',
    metric: 'travel_distance',
    name: 'First Miles',
    thresholdMi: 10,
    thresholdKm: 15,
  },
  {
    id: 'travel_50',
    pillar: 'traveler',
    metric: 'travel_distance',
    name: 'Neighborhood Nomad',
    thresholdMi: 50,
    thresholdKm: 80,
  },
  {
    id: 'travel_100',
    pillar: 'traveler',
    metric: 'travel_distance',
    name: 'Century Road',
    thresholdMi: 100,
    thresholdKm: 160,
  },
  {
    id: 'travel_250',
    pillar: 'traveler',
    metric: 'travel_distance',
    name: 'Regional Rover',
    thresholdMi: 250,
    thresholdKm: 400,
  },
  {
    id: 'travel_500',
    pillar: 'traveler',
    metric: 'travel_distance',
    name: 'Half-Thousand',
    thresholdMi: 500,
    thresholdKm: 800,
  },
  {
    id: 'travel_1000',
    pillar: 'traveler',
    metric: 'travel_distance',
    name: 'Thousand Roads',
    thresholdMi: 1000,
    thresholdKm: 1600,
  },
  {
    id: 'travel_2500',
    pillar: 'traveler',
    metric: 'travel_distance',
    name: 'Long Haul',
    thresholdMi: 2500,
    thresholdKm: 4000,
  },
  {
    id: 'travel_5000',
    pillar: 'traveler',
    metric: 'travel_distance',
    name: 'Cross-Country',
    thresholdMi: 5000,
    thresholdKm: 8000,
  },
  {
    id: 'travel_10000',
    pillar: 'traveler',
    metric: 'travel_distance',
    name: 'Ten Thousand',
    thresholdMi: 10000,
    thresholdKm: 16000,
  },
  {
    id: 'travel_25000',
    pillar: 'traveler',
    metric: 'travel_distance',
    name: 'World Wanderer',
    thresholdMi: 25000,
    thresholdKm: 40000,
  },

  // Explorer — places
  {
    id: 'places_5',
    pillar: 'explorer',
    metric: 'unique_places',
    name: 'Getting Out',
    threshold: 5,
  },
  {
    id: 'places_10',
    pillar: 'explorer',
    metric: 'unique_places',
    name: 'Local Explorer',
    threshold: 10,
  },
  {
    id: 'places_25',
    pillar: 'explorer',
    metric: 'unique_places',
    name: 'City Sampler',
    threshold: 25,
  },
  {
    id: 'places_50',
    pillar: 'explorer',
    metric: 'unique_places',
    name: 'Fifty Stops',
    threshold: 50,
  },
  {
    id: 'places_100',
    pillar: 'explorer',
    metric: 'unique_places',
    name: 'Hundred Places',
    threshold: 100,
  },
  {
    id: 'places_250',
    pillar: 'explorer',
    metric: 'unique_places',
    name: 'Deep Map',
    threshold: 250,
  },
  {
    id: 'places_500',
    pillar: 'explorer',
    metric: 'unique_places',
    name: 'Atlas Builder',
    threshold: 500,
  },

  // Explorer — POI category firsts
  {
    id: 'cat_cafe',
    pillar: 'explorer',
    metric: 'poi_category',
    name: 'First Café',
    threshold: 1,
    poiCategoryKeys: ['cafe'],
  },
  {
    id: 'cat_restaurant',
    pillar: 'explorer',
    metric: 'poi_category',
    name: 'First Restaurant',
    threshold: 1,
    poiCategoryKeys: ['restaurant'],
  },
  {
    id: 'cat_bakery',
    pillar: 'explorer',
    metric: 'poi_category',
    name: 'First Bakery',
    threshold: 1,
    poiCategoryKeys: ['bakery'],
  },
  {
    id: 'cat_park',
    pillar: 'explorer',
    metric: 'poi_category',
    name: 'First Park',
    threshold: 1,
    poiCategoryKeys: ['park', 'nationalPark'],
  },
  {
    id: 'cat_beach',
    pillar: 'explorer',
    metric: 'poi_category',
    name: 'First Beach',
    threshold: 1,
    poiCategoryKeys: ['beach'],
  },
  {
    id: 'cat_airport',
    pillar: 'explorer',
    metric: 'poi_category',
    name: 'First Airport',
    threshold: 1,
    poiCategoryKeys: ['airport'],
  },
  {
    id: 'cat_hotel',
    pillar: 'explorer',
    metric: 'poi_category',
    name: 'First Hotel',
    threshold: 1,
    poiCategoryKeys: ['hotel'],
  },
  {
    id: 'cat_gym',
    pillar: 'explorer',
    metric: 'poi_category',
    name: 'First Gym',
    threshold: 1,
    poiCategoryKeys: ['fitnessCenter'],
  },
  {
    id: 'cat_store',
    pillar: 'explorer',
    metric: 'poi_category',
    name: 'First Store',
    threshold: 1,
    poiCategoryKeys: ['store', 'foodMarket'],
  },
  {
    id: 'cat_gas',
    pillar: 'explorer',
    metric: 'poi_category',
    name: 'First Fill-Up',
    threshold: 1,
    poiCategoryKeys: ['gasStation'],
  },
  {
    id: 'cat_hospital',
    pillar: 'explorer',
    metric: 'poi_category',
    name: 'First Hospital',
    threshold: 1,
    poiCategoryKeys: ['hospital'],
  },
  {
    id: 'cat_library',
    pillar: 'explorer',
    metric: 'poi_category',
    name: 'First Library',
    threshold: 1,
    poiCategoryKeys: ['library'],
  },

  // Rhythm
  {
    id: 'days_7',
    pillar: 'rhythm',
    metric: 'days_tracked',
    name: 'First Week',
    threshold: 7,
  },
  {
    id: 'days_30',
    pillar: 'rhythm',
    metric: 'days_tracked',
    name: 'First Month',
    threshold: 30,
  },
  {
    id: 'days_100',
    pillar: 'rhythm',
    metric: 'days_tracked',
    name: 'Hundred Days',
    threshold: 100,
  },
  {
    id: 'days_365',
    pillar: 'rhythm',
    metric: 'days_tracked',
    name: 'Year of You',
    threshold: 365,
  },
  {
    id: 'nights_1',
    pillar: 'rhythm',
    metric: 'nights_away',
    name: 'Night Out',
    threshold: 1,
  },
  {
    id: 'moments_1',
    pillar: 'rhythm',
    metric: 'moments_total',
    name: 'First Moment',
    threshold: 1,
  },
  {
    id: 'moments_10',
    pillar: 'rhythm',
    metric: 'moments_total',
    name: 'Moment Keeper',
    threshold: 10,
  },
  {
    id: 'moments_25',
    pillar: 'rhythm',
    metric: 'moments_total',
    name: 'Story Starting',
    threshold: 25,
  },
  {
    id: 'moments_50',
    pillar: 'rhythm',
    metric: 'moments_total',
    name: 'Fifty Memories',
    threshold: 50,
  },
  {
    id: 'moments_100',
    pillar: 'rhythm',
    metric: 'moments_total',
    name: 'Hundred Moments',
    threshold: 100,
  },
  {
    id: 'moments_250',
    pillar: 'rhythm',
    metric: 'moments_total',
    name: 'Life Archive',
    threshold: 250,
  },
  {
    id: 'moment_photo_1',
    pillar: 'rhythm',
    metric: 'moments_kind',
    name: 'First Photo',
    threshold: 1,
    momentKind: 'photo',
  },
  {
    id: 'moment_video_1',
    pillar: 'rhythm',
    metric: 'moments_kind',
    name: 'First Clip',
    threshold: 1,
    momentKind: 'video',
  },
  {
    id: 'moment_note_1',
    pillar: 'rhythm',
    metric: 'moments_kind',
    name: 'First Note',
    threshold: 1,
    momentKind: 'note',
  },
  {
    id: 'moment_voice_1',
    pillar: 'rhythm',
    metric: 'moments_kind',
    name: 'First Voice',
    threshold: 1,
    momentKind: 'voice',
  },
  {
    id: 'moment_mood_1',
    pillar: 'rhythm',
    metric: 'moments_kind',
    name: 'First Mood',
    threshold: 1,
    momentKind: 'mood',
  },
  {
    id: 'moment_activity_1',
    pillar: 'rhythm',
    metric: 'moments_kind',
    name: 'First Activity',
    threshold: 1,
    momentKind: 'activity',
  },
  {
    id: 'activities_10',
    pillar: 'rhythm',
    metric: 'activities_count',
    name: 'Habit Starter',
    threshold: 10,
  },
  {
    id: 'activities_50',
    pillar: 'rhythm',
    metric: 'activities_count',
    name: 'Habit Keeper',
    threshold: 50,
  },
  {
    id: 'home_set',
    pillar: 'rhythm',
    metric: 'home_set',
    name: 'Home Base',
    threshold: 1,
  },
  {
    id: 'work_set',
    pillar: 'rhythm',
    metric: 'work_set',
    name: 'Work Anchor',
    threshold: 1,
  },
  {
    id: 'home_fullday_1',
    pillar: 'rhythm',
    metric: 'home_fullday',
    name: 'Full Day Home',
    threshold: 1,
  },
  {
    id: 'home_fullday_5',
    pillar: 'rhythm',
    metric: 'home_fullday',
    name: 'Nesting',
    threshold: 5,
  },
  {
    id: 'home_fullday_10',
    pillar: 'rhythm',
    metric: 'home_fullday',
    name: 'Homebody',
    threshold: 10,
  },
  {
    id: 'home_fullday_25',
    pillar: 'rhythm',
    metric: 'home_fullday',
    name: 'Deep Roots',
    threshold: 25,
  },
] as const;

export const ACHIEVEMENT_BADGE_BY_ID = Object.fromEntries(
  ACHIEVEMENT_BADGES.map(badge => [badge.id, badge]),
) as Record<
  (typeof ACHIEVEMENT_BADGES)[number]['id'],
  AchievementBadgeDefinition
>;

export function badgesForPillar(
  pillar: AchievementBadgeDefinition['pillar'],
): readonly AchievementBadgeDefinition[] {
  return ACHIEVEMENT_BADGES.filter(badge => badge.pillar === pillar);
}
